name: Deploy Nyx-capaign_dashboard environment
run-name:  Nyx-capaign_dashboard Deployment environment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout Code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Deploy via SSH
      - name: Deploy Code to Server
        uses: appleboy/ssh-action@v1.2.0
        env:
            GH_PERSONAL_ACCESS_TOKEN: ${{secrets.GH_REPO_TOKEN}}
        
            
        with:
          host: ${{ vars.DEV_SERVER_SSH_HOST_IP }}
          envs: GH_PERSONAL_ACCESS_TOKEN
          username: ${{ vars.DEV_SERVER_SSH_USER }}
          password: ${{ secrets.DEV_SERVER_SSH_PASSWORD }}
          debug: true
          script_path:  scripts/deploy-prod.sh
          